### ISSUE TITLE
Throws on an empty object without prototype

### ISSUE THREAD

**Issue by futpib** [SkeLLLa/node-object-hash#11]
```js
require('node-object-hash')().hash(Object.create(null))
```
```
TypeError: Cannot read property 'name' of undefined
    at _guessObjectType (.../node-object-hash/objectSorter.js:20:27)
    at _guessType (.../node-object-hash/objectSorter.js:68:37)
    at objectToString (.../node-object-hash/objectSorter.js:213:24)
    at sortObject (.../node-object-hash/index.js:78:12)
    at Object.hashObject [as hash] (.../node-object-hash/index.js:103:18
```

Here is the offending line (20): https://github.com/SkeLLLa/node-object-hash/blob/0ac4d886f85a1a4053e67e5c2a24ddc4ae299bad/objectSorter.js#L15-L21

This assumes that every (non-null) object has as `constructor` property, which is not generally the case.

**Comment by SkeLLLa** [comment]
@futpib 
Published as v1.4.0 https://www.npmjs.com/package/node-object-hash/v/1.4.0
